#pragma once
// Particle systems the sparkle picker offers (#133): the usable catalogue of `just data fx` (82 Cascade systems, 2026-10-10),
// the first kCurated being sparkle-like (loop, small, emissive). Baked: the picker never walks GObjects. `colour` = the
// material vector parameter of emitter 0 that carries the tint ("" = fixed colour: no tint), `extra` = more parameters
// set to the same colour (nullptr-terminated), `gain` = x on the HDR-scaled emissive (idle_loot::kGlow) for that material.
#include <cstddef>

namespace idle_loot {
    struct Template { const char* name; const wchar_t* path; const wchar_t* colour; const wchar_t* extra[4]; float gain; };
    constexpr std::size_t kCurated = 9;
    constexpr Template kTemplates[] = {
        {"hp_mag_alchemyOrb_fireflies", L"/Game/Environments/HumanProps/Magic/Particles/hp_mag_alchemyOrb_fireflies.hp_mag_alchemyOrb_fireflies", L"Emissive Thorax", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_fireFlies", L"/Game/FX/Environmental/Particles/fx_fireFlies.fx_fireFlies", L"Emissive Thorax", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"hp_mag_alchemyOrb_butterfly", L"/Game/Environments/HumanProps/Magic/Particles/hp_mag_alchemyOrb_butterfly.hp_mag_alchemyOrb_butterfly", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Champion_HandGlow_01", L"/Game/FX/Classes/Champion/Particles/P_Champion_HandGlow_01.P_Champion_HandGlow_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_StaffGlow_01", L"/Game/FX/Classes/Wizard/Particles/P_StaffGlow_01.P_StaffGlow_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_ky_aura_yellow", L"/Game/Marketplace/AdvancedMagicFX12/particles/P_ky_aura_yellow.P_ky_aura_yellow", L"dustColor", {L"hilightColor", L"lowLightColor", nullptr, nullptr}, 0.0004f},
        {"P_ky_pool", L"/Game/Marketplace/AdvancedMagicFX12/particles/P_ky_pool.P_ky_pool", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"FX_Fire_Skeleton__Embers", L"/Game/FX/Enemies/FX_Fire_Skeleton__Embers.FX_Fire_Skeleton__Embers", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PS_PurpleLantern_ImmunityBubbles", L"/Game/Blueprints/Characters/AI/Abilities/AbilityTemplatesDoS/PurpleLantern/PS_PurpleLantern_ImmunityBubbles.PS_PurpleLantern_ImmunityBubbles", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_potion", L"/Game/Blueprints/Ability/Abilities/Generic/UsePotion/fx_potion.fx_potion", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"ArrowEffect", L"/Game/FX/Arrow/Particles/ArrowEffect.ArrowEffect", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"HemlockArrowEffect", L"/Game/FX/Arrow/Particles/HemlockArrowEffect.HemlockArrowEffect", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"MultiShotArrowEffect", L"/Game/FX/Arrow/Particles/MultiShotArrowEffect.MultiShotArrowEffect", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PoisonArrowEffect4", L"/Game/FX/Arrow/Particles/PoisonArrowEffect4.PoisonArrowEffect4", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"BoulderEffect", L"/Game/FX/Boulder/Particles/BoulderEffect.BoulderEffect", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Champion_Cleave_01", L"/Game/FX/Classes/Champion/Particles/P_Champion_Cleave_01.P_Champion_Cleave_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Champion_MightyBlow_01", L"/Game/FX/Classes/Champion/Particles/P_Champion_MightyBlow_01.P_Champion_MightyBlow_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Champion_fist_01", L"/Game/FX/Classes/Champion/Particles/P_Champion_fist_01.P_Champion_fist_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_champ_charge", L"/Game/FX/Classes/Champion/Particles/fx_champ_charge.fx_champ_charge", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_champ_skinOfStone", L"/Game/FX/Classes/Champion/Particles/fx_champ_skinOfStone.fx_champ_skinOfStone", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_cheiftain_skinofice", L"/Game/FX/Classes/Chieftain/fx_cheiftain_skinofice.fx_cheiftain_skinofice", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"FX_Blood_drip_01", L"/Game/FX/Classes/Delivered_11_9/FX_Blood_drip_01.FX_Blood_drip_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Ranger_Arrow", L"/Game/FX/Classes/Ranger/Particles/P_Ranger_Arrow.P_Ranger_Arrow", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Ranger_Arrow_Green", L"/Game/FX/Classes/Ranger/Particles/P_Ranger_Arrow_Green.P_Ranger_Arrow_Green", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Rogue_Stun_hit_02", L"/Game/FX/Classes/Rogue/Particles/P_Rogue_Stun_hit_02.P_Rogue_Stun_hit_02", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Rogue_trail_03", L"/Game/FX/Classes/Rogue/Particles/P_Rogue_trail_03.P_Rogue_trail_03", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Rogue_trail_04", L"/Game/FX/Classes/Rogue/Particles/P_Rogue_trail_04.P_Rogue_trail_04", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_rogue_hamstring", L"/Game/FX/Classes/Rogue/Particles/fx_rogue_hamstring.fx_rogue_hamstring", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_rogue_throwDagger", L"/Game/FX/Classes/Rogue/Particles/fx_rogue_throwDagger.fx_rogue_throwDagger", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_shaman_reverberation_cast", L"/Game/FX/Classes/Shaman/fx_shaman_reverberation_cast.fx_shaman_reverberation_cast", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_AnimTrail_01", L"/Game/FX/Classes/Wizard/Particles/P_AnimTrail_01.P_AnimTrail_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_Vortex_Souls_Swirl", L"/Game/FX/Dungeons/IcyDepths/fx_Vortex_Souls_Swirl.fx_Vortex_Souls_Swirl", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Banshee_trail_01", L"/Game/FX/Enemies/Banshee/Particles/P_Banshee_trail_01.P_Banshee_trail_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Banshee_trail_02", L"/Game/FX/Enemies/Banshee/Particles/P_Banshee_trail_02.P_Banshee_trail_02", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Banshee_trail_03", L"/Game/FX/Enemies/Banshee/Particles/P_Banshee_trail_03.P_Banshee_trail_03", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"FX_Fire_Blue_Skeleton", L"/Game/FX/Enemies/FX_Fire_Blue_Skeleton.FX_Fire_Blue_Skeleton", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"FX_Fire_Blue_Skeleton__Embers", L"/Game/FX/Enemies/FX_Fire_Blue_Skeleton__Embers.FX_Fire_Blue_Skeleton__Embers", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"FX_Fire_Skeleton", L"/Game/FX/Enemies/FX_Fire_Skeleton.FX_Fire_Skeleton", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Minotaur_charge_01", L"/Game/FX/Enemies/Minotaur/Particles/P_Minotaur_charge_01.P_Minotaur_charge_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Eye_fire_01", L"/Game/FX/Enemies/P_Eye_fire_01.P_Eye_fire_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Eye_green_01", L"/Game/FX/Enemies/P_Eye_green_01.P_Eye_green_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Eye_ice_01", L"/Game/FX/Enemies/P_Eye_ice_01.P_Eye_ice_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Eye_purple_01", L"/Game/FX/Enemies/P_Eye_purple_01.P_Eye_purple_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Eye_red_01", L"/Game/FX/Enemies/P_Eye_red_01.P_Eye_red_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Eye_yellow_01", L"/Game/FX/Enemies/P_Eye_yellow_01.P_Eye_yellow_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_SkeletonKing_Pull_Target", L"/Game/FX/Enemies/SkeletonKing/fx_SkeletonKing_Pull_Target.fx_SkeletonKing_Pull_Target", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_SPiderQueen_trail_01", L"/Game/FX/Enemies/SpiderQueen/Particles/P_SPiderQueen_trail_01.P_SPiderQueen_trail_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_GodRays_01", L"/Game/FX/Environmental/Particles/P_GodRays_01.P_GodRays_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_RedGlass_smoke_01", L"/Game/FX/Environmental/Particles/P_RedGlass_smoke_01.P_RedGlass_smoke_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_butterflyGreen_med", L"/Game/FX/Environmental/Particles/fx_butterflyGreen_med.fx_butterflyGreen_med", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_env_crawlingSpiders_med", L"/Game/FX/Environmental/Particles/fx_env_crawlingSpiders_med.fx_env_crawlingSpiders_med", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"FX_FlameWave_Bottom", L"/Game/FX/Fire/Particles/FX_FlameWave_Bottom.FX_FlameWave_Bottom", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"FX_IceWave_Bottom", L"/Game/FX/Fire/Particles/FX_IceWave_Bottom.FX_IceWave_Bottom", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_fireTorch", L"/Game/FX/Fire/Particles/fx_fireTorch.fx_fireTorch", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_fireTorch_Green", L"/Game/FX/Fire/Particles/fx_fireTorch_Green.fx_fireTorch_Green", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_smokeTorch", L"/Game/FX/Fire/Particles/fx_smokeTorch.fx_smokeTorch", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_Ability_Enh_DeadlyAim_Debuff", L"/Game/FX/GameplayEffect/Particles/fx_Ability_Enh_DeadlyAim_Debuff.fx_Ability_Enh_DeadlyAim_Debuff", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_lens_stunned", L"/Game/FX/LensEffects/Particles/fx_lens_stunned.fx_lens_stunned", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_ChannelMagic", L"/Game/FX/Magic/Particles/fx_ChannelMagic.fx_ChannelMagic", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_ChannelMagic_Drain", L"/Game/FX/Magic/Particles/fx_ChannelMagic_Drain.fx_ChannelMagic_Drain", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_HolyLightTrail", L"/Game/FX/Magic/Particles/fx_HolyLightTrail.fx_HolyLightTrail", L"Emissive Color", {L"TC_1", L"TC_2", L"TC_3", nullptr}, 0.0012f},
        {"fx_smokeStandard01", L"/Game/FX/Smoke/Particles/fx_smokeStandard01.fx_smokeStandard01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_smoke_darkA", L"/Game/FX/Smoke/Particles/fx_smoke_darkA.fx_smoke_darkA", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"fx_smoke_grayA_HUB", L"/Game/FX/Smoke/Particles/fx_smoke_grayA_HUB.fx_smoke_grayA_HUB", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Trail_fire_01", L"/Game/FX/WeaponFx/Particles/Fire/P_Trail_fire_01.P_Trail_fire_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"P_Trail_holy_01", L"/Game/FX/WeaponFx/Particles/Holy/P_Trail_holy_01.P_Trail_holy_01", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PS_GPS_Buff_Trail_Ice02", L"/Game/Marketplace/GoodParticleStatus/Particles/Buff_Status/PS_GPS_Buff_Trail_Ice02.PS_GPS_Buff_Trail_Ice02", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PS_GPS_Buff_Trail_Poison_Purple", L"/Game/Marketplace/GoodParticleStatus/Particles/Buff_Status/PS_GPS_Buff_Trail_Poison_Purple.PS_GPS_Buff_Trail_Poison_Purple", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PS_GPS_Buff_Trail_Poison_Red", L"/Game/Marketplace/GoodParticleStatus/Particles/Buff_Status/PS_GPS_Buff_Trail_Poison_Red.PS_GPS_Buff_Trail_Poison_Red", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PS_GPS_Buff_Trail_Poison_White", L"/Game/Marketplace/GoodParticleStatus/Particles/Buff_Status/PS_GPS_Buff_Trail_Poison_White.PS_GPS_Buff_Trail_Poison_White", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PS_GPS_SimpleSmoke_Aqua", L"/Game/Marketplace/GoodParticleStatus/Particles/Buff_Status/PS_GPS_SimpleSmoke_Aqua.PS_GPS_SimpleSmoke_Aqua", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PS_GPS_SimpleSmoke_Blue", L"/Game/Marketplace/GoodParticleStatus/Particles/Buff_Status/PS_GPS_SimpleSmoke_Blue.PS_GPS_SimpleSmoke_Blue", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PS_GPS_SimpleSmoke_DarkGreen", L"/Game/Marketplace/GoodParticleStatus/Particles/Buff_Status/PS_GPS_SimpleSmoke_DarkGreen.PS_GPS_SimpleSmoke_DarkGreen", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PS_GPS_SimpleSmoke_Green", L"/Game/Marketplace/GoodParticleStatus/Particles/Buff_Status/PS_GPS_SimpleSmoke_Green.PS_GPS_SimpleSmoke_Green", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PS_GPS_SimpleSmoke_Orange", L"/Game/Marketplace/GoodParticleStatus/Particles/Buff_Status/PS_GPS_SimpleSmoke_Orange.PS_GPS_SimpleSmoke_Orange", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PS_GPS_SimpleSmoke_Purple", L"/Game/Marketplace/GoodParticleStatus/Particles/Buff_Status/PS_GPS_SimpleSmoke_Purple.PS_GPS_SimpleSmoke_Purple", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PS_GPS_SimpleSmoke_Red", L"/Game/Marketplace/GoodParticleStatus/Particles/Buff_Status/PS_GPS_SimpleSmoke_Red.PS_GPS_SimpleSmoke_Red", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"PS_GPS_SimpleSmoke_White", L"/Game/Marketplace/GoodParticleStatus/Particles/Buff_Status/PS_GPS_SimpleSmoke_White.PS_GPS_SimpleSmoke_White", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"Fire_20_Blue_B", L"/Game/Marketplace/M5VFXVOL2/Particles/Fire/Fire_20_Blue_B.Fire_20_Blue_B", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"Fire_20_Purple_B", L"/Game/Marketplace/M5VFXVOL2/Particles/Fire/Fire_20_Purple_B.Fire_20_Purple_B", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"Fire_21", L"/Game/Marketplace/M5VFXVOL2/Particles/Fire/Fire_21.Fire_21", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
        {"2_bonefire2B_fwd2_pt", L"/Game/Marketplace/M5VFXVOL2/Particles/Reference/Fireloop/2_bonefire2B_fwd2_pt.2_bonefire2B_fwd2_pt", L"", {nullptr, nullptr, nullptr, nullptr}, 1.0f},
    };
    constexpr std::size_t kTemplateCount = sizeof kTemplates / sizeof *kTemplates;
}
